### ISSUE TITLE
Add forum navigation to bottom 

### ISSUE THREAD

**Issue by sam563** [pippinmole/Illusive#15]
![image](https://user-images.githubusercontent.com/56520174/99298729-10382680-2842-11eb-9ba6-fc43f2a8f851.png)
Add these buttons to the bottom of the forums page to make navigation easier.

**Comment by pippinmole** [comment]
Hi,

This issue has been fixed in [this](https://github.com/pippinmole/Illusive/commit/25220d18d327dddd0d3264ecec0bd1e7a6c18fa6) commit.

Thank you for your feedback!
