### ISSUE TITLE
Disable (Previous / Next) buttons when there is no previous / next page

### ISSUE THREAD

**Issue by sam563** [pippinmole/Illusive#16]
Should not be able to interact with the previous / next buttons when the page does not exist!
- Grey out the button and make it none intractable in the case it doesn't have a page to go to

**Comment by pippinmole** [comment]
Hi

This issue has been fixed alongside [this](https://github.com/pippinmole/Illusive/issues/15) issue [here](https://github.com/pippinmole/Illusive/commit/25220d18d327dddd0d3264ecec0bd1e7a6c18fa6).

Thank you for your feedback!
