### ISSUE TITLE
Additional options for sorting forum threads

### ISSUE THREAD

**Issue by sam563** [pippinmole/Illusive#17]
Add additional Ascending / Descending dropdown to make sorting and navigation easier and more convenient.
![image](https://user-images.githubusercontent.com/56520174/99300373-6b6b1880-2844-11eb-9963-7e486305e51f.png)

**Comment by pippinmole** [comment]
Hi

Thank you for your suggestion, it has been added [here](https://github.com/pippinmole/Illusive/commit/6304d17cc32d8b0c9c9dae263443c2646fc82f7f).
