### ISSUE TITLE
[Mobile] Notification panel opens toward the right, covering half the screen

### ISSUE THREAD

**Issue by ibra** [pippinmole/Illusive#34]
![image](https://user-images.githubusercontent.com/61324615/100726514-da20a800-33e6-11eb-968a-1bb9a509b97d.png)

A solution to this could be making it smaller, or opening it to the left

**Comment by minidevz** [comment]
Wait nevermind im dumb, i cleared cache and its fine now

**Comment by minidevz** [comment]
Also this is a problem only with mobile, not browser**
