### ISSUE TITLE
Add option to delete posts or deactivate account

### ISSUE THREAD

**Issue by sam563** [pippinmole/Illusive#9]
Option to remove a forum post or a comment on a post and the option to disable an account

**Comment by pippinmole** [comment]
Added post deletion [here](https://github.com/pippinmole/Illusive/commit/6f6be816ebf35bbfd8139555d95db4716a89a00f)

**Comment by pippinmole** [comment]
Hi,

This has been added in [this](https://github.com/pippinmole/Illusive/commit/fec3bd061edb859cbc5fa9f6a4824f5b4a49d812) commit.

Thank you for your feedback.
